#!/bin/sh
# $2 - Port
# $4 - origin
# $6 - name
# $8 - username
# $10 - keyfile

#echo $2
#echo $4
#echo $6
#echo $8
#echo $10

dnsserver=cs5700cdnproject.ccs.neu.edu


ssh -i $10 -n -f $8@$dnsserver "./dnsserver -p $2 -n $6"

ssh -i $10 -n -f $8@ec2-52-0-73-113.compute-1.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-16-219-28.eu-west-1.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-11-8-29.us-west-2.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-8-12-101.us-west-1.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-28-48-84.eu-central-1.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com "./httpserver -p $2 -o $4"

ssh -i $10 -n -f $8@ec2-54-94-214-108.sa-east-1.compute.amazonaws.com "./httpserver -p $2 -o $4"
