#!/bin/sh
# $2 - Port
# $4 - origin
# $6 - name
# $8 - username
# $10 - keyfile
#echo $2
#echo $4
#echo $6
#echo $8
#echo $10
ssh -i $10 $8@cs5700cdnproject.ccs.neu.edu 'killall python' > /dev/null
ssh -i $10 $8@cs5700cdnproject.ccs.neu.edu 'killall freegeoip' > /dev/null
ssh -i $10 $8@ec2-52-0-73-113.compute-1.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-16-219-28.eu-west-1.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-11-8-29.us-west-2.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-8-12-101.us-west-1.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-28-48-84.eu-central-1.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com 'killall python' > /dev/null
ssh -i $10 $8@ec2-54-94-214-108.sa-east-1.compute.amazonaws.com 'killall python' > /dev/null